version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      MEMORY: 6G
      EULA: "TRUE"
      TYPE: MODRINTH
      MODRINTH_PROJECT: https://modrinth.com/modpack/sop
      # or for auto-upgrading to latest
      # MODRINTH_PROJECT: https://modrinth.com/modpack/cobblemon-fabric
      # or just cobblemon-fabric or 5FFgwNNP
      # and could replace version URL with
      # MODRINTH_VERSION: nvrqJg44
      MODRINTH_VERSION: 1.20.1-1.2.0
      # MODRINTH_VERSION: "Cobblemon [Fabric] 1.3.2"
      SETUP_ONLY: "true"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data
